### ISSUE TITLE
Is DAVIS datasets necessary for this project?

### ISSUE THREAD

**Issue by lordbutters** [chuchienshu/Colorization#3]
I wanna to run your project, I have already download Image2012 dataset, but  **_frame_utils.py_** shows that I have to download DAVIS dataset, and I find DAVIS is a video dataset. **_It really confuses me_**. Can you tell me what should I do? Where can I get the DAVIS_test picture?

**Comment by chuchienshu** [comment]
Q1: any high-quality dataset is encouraged. All you need do is modify part of the image loading code.
Q2: pictures never used in the training phase can be considered as test data.
