### ISSUE TITLE
where are some code about T=0.38

### ISSUE THREAD

**Issue by ghost** [chuchienshu/Colorization#4]
Think you code,and:

In paper,  having the data that   T=0.38,but, I can't find T in your code。I believe it exist, please tell me,where is  T.

**Comment by Callifrey** [comment]
In the original paper, temprature T is used to map  predicted distribution to point estimate in ab space(real color gamut), but in this implement,  it just take the mode of predicted distribution, which have the equal effect to T=1.0.

**Comment by yyyzzzhao** [comment]
Actually, T is applied in this repo. The output scores mul 2.63, which is the reciprocal  of 0.38. In raw caffe implementation, there 2 ways to estimate T
1. The author set one Reheat8 layer with shape (1, 313, 56, 56) to learn the annealing temperature T;
2. According to experience, there is an optimal T=0.38, which means all (1, 313, 56, 56) variables equal to 1/0.38=2.63 and the conv8 output mul 2.63 in point-wise.
Referring to this link [https://github.com/richzhang/colorization/blob/caffe/models/colorization_deploy_v1.prototxt](url)

**Comment by ghost** [comment]
> 
> 
> Actually, T is applied in this repo. The output scores mul 2.63, which is the reciprocal of 0.38. In raw caffe implementation, there 2 ways to estimate T
> 
>     1. The author set one Reheat8 layer with shape (1, 313, 56, 56) to learn the annealing temperature T;
> 
>     2. According to experience, there is an optimal T=0.38, which means all (1, 313, 56, 56) variables equal to 1/0.38=2.63 and the conv8 output mul 2.63 in point-wise.
>        Referring to this link [https://github.com/richzhang/colorization/blob/caffe/models/colorization_deploy_v1.prototxt](url)

think you
